---
    - name: ENABLE REQUIRED FEATURES
      nxos_feature:
        feature: "{{ item.feature }}"
      with_items: "{{ features }}"

    - name: CHANGE INTERFACES to L3 Mode 
      nxos_interface:
        interface: "{{ item.name }}"
        mode: layer3
      with_items: "{{ interfaces }}"

    - name: CONFIGURE IP ADDRESSES ON INTERFACES
      nxos_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}"
      with_items: 
      - "{{ interfaces }}"
      - "{{ loopbacks }}"