# Push Firewall rule 
---

- name: Palo Alto FW Rule Updates 
  hosts: palo
  connection: local

  collections:
    - paloaltonetworks.panos

  tasks: 
    - name: Add test rule 1 to the firewall
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'Ansible test 1' #<source zone>-to-<dest zone>-<change ref>
        #description: 'An Ansible test rule'
        source_zone: ['INSIDE']
        destination_zone: ['Outside']
        source_ip: ['1.2.3.4']
        source_user: ['any']
        destination_ip: ['any']
        category: ['any']
        application: ['any']
        service: ['service-http']
        hip_profiles: ['any']
        action: 'allow'
        commit: 'False'

    - name: Add test rule 2 to the firewall
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'Ansible test 2'
        description: 'An Ansible test rule'
        source_zone: ['INSIDE']
        destination_zone: ['Outside']
        source_ip: ['1.2.3.7']
        source_user: ['any']
        destination_ip: ['any']
        category: ['any']
        application: ['any']
        service: ['service-https']
        hip_profiles: ['any']
        action: 'allow'
        commit: 'False'

    # permit dns to 1.1.1.1
    - name: permit dns to 1.1.1.1
      panos_security_rule:
        provider: "{{ palo_provider }}"
        # device_group: "{{ device_group }}" For Panos 
        rule_name: 'DNS permit'
        description: 'DNS rule test'
        source_zone: ['INSIDE']
        destination_zone: ['Outside']
        source_ip: ['any']
        source_user: ['any']
        destination_ip: ['1.1.1.1']
        category: ['any']
        application: ['dns']
        service: ['application-default']
        hip_profiles: ['any']
        action: 'allow'
        state: 'present'
        commit: false

    - name: Add the service object to the firewall first
      panos_service_object:
        provider: '{{ palo_provider }}'
        name: 'service-tcp-221'
        protocol: 'tcp'
        destination_port: '221'
        description: 'SSH on port 221'
        #tag: ['Prod'] "TAG needs to be defined first"
        commit: false

    - name: Create dynamic NAT rule on the firewall
      panos_nat_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'Ansible test 1'
        source_zone: ['INSIDE']
        destination_zone: 'Outside'
        source_ip: ['any']
        destination_ip: ['10.1.1.1']
        service: 'service-tcp-221'
        snat_type: 'dynamic-ip-and-port'
        snat_interface: 'ethernet1/2'
        dnat_address: '10.10.10.1'
        dnat_port: '22'



