---
- hosts: uklabaci
  connection: local
  gather_facts: no
  vars_files:
  - ../group_vars/aci-variables.yaml
  tasks:
    - name: Create Bridge Domain {{ bd_name }}
      cisco.aci.aci_bd:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ aci_tenant }}"
        bd: "{{ bd_name }}"
        mac_address: 00:22:BD:F8:19:FE
        vrf: "{{ aci_vrf }}"
        state: present
      delegate_to: localhost
    - name: Create a subnet for the bridge domain {{ bd_name }}
      cisco.aci.aci_bd_subnet:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ aci_tenant }}"
        bd: "{{ bd_name }}"
        gateway: "{{ bd_gateway }}"
        mask: 24
        state: present
      delegate_to: localhost