---
- name: Convert configured OSPFV2 resource to structured data
  hosts: CSR_Routers 

  gather_facts: false
  tasks:

  - name: Create inventory directory if not exist 
    file:
      path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
      state: directory

# Pull current OSPFv2 config 

  - name: Use the OSPFV2 resource module to gather the current config
    cisco.ios.ios_ospfv2:
      config: 
      state: gathered
    register: ospfv2

  - name: Write the OSPFV2 configuration to a file
    copy:
      content: "{{ {'ospfv2': ospfv2['gathered']} | to_nice_yaml }}"
      dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/ospfv2.yaml"

